# Generated by Django 3.2.6 on 2022-05-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_desciption_movie_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=250)),
                ('cover_photo', models.ImageField(upload_to='upcoming_covers/')),
                ('video', models.FileField(upload_to='upcoming_covers/')),
                ('description', models.TextField(max_length=300)),
                ('release_date', models.DateField()),
                ('slug', models.SlugField()),
                ('genre', models.ManyToManyField(to='mainapp.Genre')),
            ],
        ),
        migrations.RemoveField(
            model_name='season',
            name='tvshow',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.DeleteModel(
            name='Trailer',
        ),
        migrations.DeleteModel(
            name='TvShow',
        ),
    ]
